name: docker-image

on:
  workflow_dispatch:

jobs:
  docker_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Build Metadata
        run: |
          echo VERSION=`git describe --tags --always --dirty` >> $GITHUB_ENV
          echo COMMIT=`git rev-parse --short HEAD` >> $GITHUB_ENV
          echo BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ` >> $GITHUB_ENV
      - name: Build and export (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: cli-proxy-api:latest-amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          outputs: type=docker,dest=/tmp/cli-proxy-api-amd64.tar
      - name: Upload artifact (amd64)
        uses: actions/upload-artifact@v4
        with:
          name: cli-proxy-api-amd64
          path: /tmp/cli-proxy-api-amd64.tar

  docker_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Build Metadata
        run: |
          echo VERSION=`git describe --tags --always --dirty` >> $GITHUB_ENV
          echo COMMIT=`git rev-parse --short HEAD` >> $GITHUB_ENV
          echo BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ` >> $GITHUB_ENV
      - name: Build and export (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: cli-proxy-api:latest-arm64
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          outputs: type=docker,dest=/tmp/cli-proxy-api-arm64.tar
      - name: Upload artifact (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: cli-proxy-api-arm64
          path: /tmp/cli-proxy-api-arm64.tar